---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
df<-read.csv("activity.csv")
###process as date
df$date<-ymd(df$date) 

## What is mean total number of steps taken per day?
### using dplyr to process data for the histogram
library("dplyr") 
###intermediate step to subset what I needed
i<-df[,1:2]
 e<-i%>% 
  group_by(date)%>% 
  summarise_each(funs(sum, mean)) 
### the histogram
hist(e$mean) 
dev.off()
### estimating the mean, which turned out to be 10766.19
mean(e$sum, na.rm = T) 
### and the median, which turned out to be 10765
median(e$sum, na.rm = T) 

## What is the average daily activity pattern?
### using dplyr to make the average number of steps taken,across all days 
library("dplyr")
f<-df%>% 
  group_by(interval,date)%>% 
  summarise_each(funs(mean))
### now to ggplot it
library("ggplot2")
with(f, plot(interval, steps))
ggplot(data=f, aes(x=interval, y=steps, group=date)) +
  geom_point(aes(color=date)) + 
  geom_line(aes(color=date))
dev.off()
### finding the interval with the maximum number of steps
which.max(f$steps)
f$interval[4633]#615 is within the interval

## Imputing missing values
### mice takes care of all thing NAs
library("mice") 
###following command shows that 15,264 observations are complete, Steps have  2304 NAs
md.pattern(df)
###mice creates tempdf to take care of NAs
tempdf<-mice(df[,c(1,3)], seed=100) 
### creates vector to impute NAs to steps
tempdf$imp$steps 
### get back the completed dataset using the complete()
completedf<-complete(tempdf,1)  
###check the dims of both before passing on the imputed values
dim(completedf) 
dim(df)
df$steps<-completedf$steps passing on the imputed values
###make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day.
### using dplyr to process data for the histogram
library("dplyr") 
###intermediate step to subset what I needed
i<-df[,1:2]
 e<-i%>% 
  group_by(date)%>% 
  summarise_each(funs(sum, mean)) 
### the histogram
hist(e$mean) 
dev.off()
### estimating the mean, which turned out to be 10677.85
mean(e$sum, na.rm = T) 
### and the median, which turned out to be 10600
median(e$sum, na.rm = T) 

## Are there differences in activity patterns between weekdays and weekends?
### converts to the name of the day
df$date<-weekdays(df$date, abbreviate = F) 
### dplyr to get average number of steps taken,  across all weekday days or weekend days
library("dplyr")
g<-df%>% 
  group_by(interval,date)%>% 
  summarise_each(funs(mean))  
### logical vector for wkdy or wknd
g$logical<-ifelse(g$date=="Saturday" | g$date=="Sunday", "wknd", "wkdy") 
library("lattice")
par(mfrow=c(2,1))
###  a time series plot 
xyplot(steps ~ interval | logical, type="l", data = g, layout=c(1,2))
dev.off()    
